costructor/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registrations, :controller => 'users'
  get 'persons/profile'
  resources :roles
  resources :users_tests
  resources :users
  resources :variants do
  collection do
    get 'all'
  end
end
  resources :answers_ts
  resources :answers_ws
  get 'main/Index'
  resources :typesquestions do
  collection do
    get 'all'
  end
end
  resources :questions
  resources :types_tests
  resources :courses

  resources :tests do
    collection do
      get 'all'
    end
  end
  
  resources :showTestsToUser , :controller => 'tests', :action => 'showTestsToUser'

  root 'main#Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

costructor/app/models/answers_t.rb
class AnswersT < ApplicationRecord
    belongs_to :question,required: true,  :foreign_key => "questions_id"
    belongs_to :answers_w,required: false,  :foreign_key => "answers_ws_id"
    belongs_to :test,required: false,  :foreign_key => "tests_id"
    belongs_to :user,required: true,  :foreign_key => "users_id"
end

costructor/app/models/answers_w.rb
class AnswersW < ApplicationRecord
    belongs_to :questions,required: true,  :foreign_key => "question_id"
    has_many :answers_t
end

costructor/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

costructor/app/models/course.rb
class Course < ApplicationRecord
        has_many :test
        belongs_to :Course,optional: true,  :foreign_key => "courses_id"
        has_many :Course
end

costructor/app/models/question.rb
class Question < ApplicationRecord
    has_many :answers_t
    has_many :answers_ws, inverse_of: :questions
    belongs_to :typesquestion,required: true,  :foreign_key => "typesquestions_id"
    belongs_to :variant,required: true,  :foreign_key => "variants_id"
    belongs_to :test,required: true,  :foreign_key => "test_id"
    validates_presence_of :test
    accepts_nested_attributes_for :answers_ws
end

costructor/app/models/role.rb
class Role < ApplicationRecord
end

costructor/app/models/test.rb
class Test < ApplicationRecord
    belongs_to :types_test,required: true,  :foreign_key => "types_tests_id"
    belongs_to :course,required: true,  :foreign_key => "courses_id"
    has_many :questions, inverse_of: :test
    accepts_nested_attributes_for :questions
    has_many :users_test
    has_many :answers_t
end

costructor/app/models/types_test.rb
class TypesTest < ApplicationRecord
    has_many :test
end

costructor/app/models/typesquestion.rb
class Typesquestion < ApplicationRecord
end

costructor/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:user, :autor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :users_test
    has_many :answers_t
end

costructor/app/models/users_test.rb
class UsersTest < ApplicationRecord
    belongs_to :user,required: true,  :foreign_key => "users_id"
    belongs_to :test,required: true,  :foreign_key => "tests_id"
end

costructor/app/models/variant.rb
class Variant < ApplicationRecord
end

costructor/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:show]
  before_action :require_admin, only: [ :index, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end



  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :role)
    end
end

costructor/app/helpers/answers_ts_helper.rb
module AnswersTsHelper
end

costructor/app/helpers/answers_ws_helper.rb
module AnswersWsHelper
end

costructor/app/helpers/courses_helper.rb
module CoursesHelper
end

costructor/app/helpers/main_helper.rb
module MainHelper
end

costructor/app/helpers/persons_helper.rb
module PersonsHelper
end

costructor/app/helpers/questions_helper.rb
module QuestionsHelper
end

costructor/app/helpers/roles_helper.rb
module RolesHelper
end

costructor/app/helpers/tests_helper.rb
module TestsHelper
end

costructor/app/helpers/users_helper.rb
module UsersHelper
end

costructor/app/helpers/variants_helper.rb
module VariantsHelper
end

costructor/app/views/users/_form.html.erb
<%= form_for @user, url: registrations_path(@user)  do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :email %><br />
  <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
</div>

<div class="field">
  <%= form.label :password %>
  <% if @minimum_password_length %>
  <em>(<%= @minimum_password_length %> characters minimum)</em>
  <% end %><br />
  <%= form.password_field :password, autocomplete: "new-password" %>
</div>
<% if  !current_user.blank?  %>
<% if  current_user.role == 'admin'  %>
<div class="field">
<%= form.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
</div>
<% end %>
<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

costructor/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= form_for @user, url: registration_path(@user)  do |form| %>


        <div class="field">
        <%= form.label :email %><br />
        <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
      
      <div class="field">
        <%= form.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= form.password_field :password, autocomplete: "new-password" %>
      </div>

      <div class="field">
<%= form.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
</div>
      
        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>

costructor/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Password</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

costructor/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

costructor/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

costructor/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

costructor/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>