costructor/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registrations, :controller => 'users'
  get 'persons/profile'
  resources :roles
  resources :users_tests
  resources :users
  resources :variants do
  collection do
    get 'all'
  end
end
  resources :answers_ts
  resources :answers_ws
  get 'main/Index'
  resources :typesquestions do
  collection do
    get 'all'
  end
end
  resources :questions
  resources :types_tests
  resources :courses

  resources :tests do
    collection do
      get 'all'
    end
  end
  
  resources :showTestsToUser , :controller => 'tests', :action => 'showTestsToUser'

  root 'main#Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

costructor/app/models/answers_t.rb
class AnswersT < ApplicationRecord
    belongs_to :question,required: true,  :foreign_key => "questions_id"
    belongs_to :answers_w,required: false,  :foreign_key => "answers_ws_id"
    belongs_to :test,required: false,  :foreign_key => "tests_id"
    belongs_to :user,required: true,  :foreign_key => "users_id"
end

costructor/app/models/answers_w.rb
class AnswersW < ApplicationRecord
    belongs_to :questions,required: true,  :foreign_key => "question_id"
    has_many :answers_t
end

costructor/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

costructor/app/models/course.rb
class Course < ApplicationRecord
        has_many :test
        belongs_to :Course,optional: true,  :foreign_key => "courses_id"
        has_many :Course
end

costructor/app/models/question.rb
class Question < ApplicationRecord
    has_many :answers_t
    has_many :answers_ws, inverse_of: :questions
    belongs_to :typesquestion,required: true,  :foreign_key => "typesquestions_id"
    belongs_to :variant,required: true,  :foreign_key => "variants_id"
    belongs_to :test,required: true,  :foreign_key => "test_id"
    validates_presence_of :test
    accepts_nested_attributes_for :answers_ws
end

costructor/app/models/role.rb
class Role < ApplicationRecord
end

costructor/app/models/test.rb
class Test < ApplicationRecord
    belongs_to :types_test,required: true,  :foreign_key => "types_tests_id"
    belongs_to :course,required: true,  :foreign_key => "courses_id"
    has_many :questions, inverse_of: :test
    accepts_nested_attributes_for :questions
    has_many :users_test
    has_many :answers_t
end

costructor/app/models/types_test.rb
class TypesTest < ApplicationRecord
    has_many :test
end

costructor/app/models/typesquestion.rb
class Typesquestion < ApplicationRecord
end

costructor/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:user, :autor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :users_test
    has_many :answers_t
end

costructor/app/models/users_test.rb
class UsersTest < ApplicationRecord
    belongs_to :user,required: true,  :foreign_key => "users_id"
    belongs_to :test,required: true,  :foreign_key => "tests_id"
end

costructor/app/models/variant.rb
class Variant < ApplicationRecord
end

costructor/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :require_admin
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

costructor/app/helpers/answers_ts_helper.rb
module AnswersTsHelper
end

costructor/app/helpers/answers_ws_helper.rb
module AnswersWsHelper
end

costructor/app/helpers/courses_helper.rb
module CoursesHelper
end

costructor/app/helpers/main_helper.rb
module MainHelper
end

costructor/app/helpers/persons_helper.rb
module PersonsHelper
end

costructor/app/helpers/questions_helper.rb
module QuestionsHelper
end

costructor/app/helpers/roles_helper.rb
module RolesHelper
end

costructor/app/helpers/tests_helper.rb
module TestsHelper
end

costructor/app/helpers/users_helper.rb
module UsersHelper
end

costructor/app/helpers/variants_helper.rb
module VariantsHelper
end

costructor/app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

costructor/app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

costructor/app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

costructor/app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

costructor/app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>