costructor/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :registrations, :controller => 'users'
  get 'persons/profile'
  resources :roles
  resources :users_tests
  resources :users
  resources :variants do
  collection do
    get 'all'
  end
end
  resources :answers_ts
  resources :answers_ws
  get 'main/Index'
  resources :typesquestions do
  collection do
    get 'all'
  end
end
  resources :questions
  resources :types_tests
  resources :courses

  resources :tests do
    collection do
      get 'all'
    end
  end
  
  resources :showTestsToUser , :controller => 'tests', :action => 'showTestsToUser'

  root 'main#Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

costructor/app/models/answers_t.rb
class AnswersT < ApplicationRecord
    belongs_to :question,required: true,  :foreign_key => "questions_id"
    belongs_to :answers_w,required: false,  :foreign_key => "answers_ws_id"
    belongs_to :test,required: false,  :foreign_key => "tests_id"
    belongs_to :user,required: true,  :foreign_key => "users_id"
end

costructor/app/models/answers_w.rb
class AnswersW < ApplicationRecord
    belongs_to :questions,required: true,  :foreign_key => "question_id"
    has_many :answers_t
end

costructor/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

costructor/app/models/course.rb
class Course < ApplicationRecord
        has_many :test
        belongs_to :Course,optional: true,  :foreign_key => "courses_id"
        has_many :Course
end

costructor/app/models/question.rb
class Question < ApplicationRecord
    has_many :answers_t
    has_many :answers_ws, inverse_of: :questions
    belongs_to :typesquestion,required: true,  :foreign_key => "typesquestions_id"
    belongs_to :variant,required: true,  :foreign_key => "variants_id"
    belongs_to :test,required: true,  :foreign_key => "test_id"
    validates_presence_of :test
    accepts_nested_attributes_for :answers_ws
end

costructor/app/models/role.rb
class Role < ApplicationRecord
end

costructor/app/models/test.rb
class Test < ApplicationRecord
    belongs_to :types_test,required: true,  :foreign_key => "types_tests_id"
    belongs_to :course,required: true,  :foreign_key => "courses_id"
    has_many :questions, inverse_of: :test
    accepts_nested_attributes_for :questions
    has_many :users_test
    has_many :answers_t
end

costructor/app/models/types_test.rb
class TypesTest < ApplicationRecord
    has_many :test
end

costructor/app/models/typesquestion.rb
class Typesquestion < ApplicationRecord
end

costructor/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:user, :autor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :users_test
    has_many :answers_t
end

costructor/app/models/users_test.rb
class UsersTest < ApplicationRecord
    belongs_to :user,required: true,  :foreign_key => "users_id"
    belongs_to :test,required: true,  :foreign_key => "tests_id"
end

costructor/app/models/variant.rb
class Variant < ApplicationRecord
end

costructor/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name, :test_id, :variants_id, :typesquestions_id)
    end
end

costructor/app/helpers/answers_ts_helper.rb
module AnswersTsHelper
end

costructor/app/helpers/answers_ws_helper.rb
module AnswersWsHelper
end

costructor/app/helpers/courses_helper.rb
module CoursesHelper
end

costructor/app/helpers/main_helper.rb
module MainHelper
end

costructor/app/helpers/persons_helper.rb
module PersonsHelper
end

costructor/app/helpers/questions_helper.rb
module QuestionsHelper
end

costructor/app/helpers/roles_helper.rb
module RolesHelper
end

costructor/app/helpers/tests_helper.rb
module TestsHelper
end

costructor/app/helpers/users_helper.rb
module UsersHelper
end

costructor/app/helpers/variants_helper.rb
module VariantsHelper
end

costructor/app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type_of_question %>
    <%= form.collection_select :typesquestions_id, Typesquestion.all, :id , :name %>
  </div>

  <div class="field">
  <%= form.label :test_id %>
  <%= form.collection_select :test_id, Test.all, :id , :name %>
  </div>

  <div class="field">
  <%= form.label :variants_id %>
  <%= form.collection_select :variants_id, Variant.all, :id , :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

costructor/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

costructor/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type of question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.name %></td>
        <% @cname = Typesquestion.find_by id: question.typesquestions_id.to_i  %>
        <td><%= @cname.blank? ?  nil : @cname.name %></td>
        <% @cname = Variant.find_by id: question.variants_id.to_i  %>
        <td><%= @cname.blank? ?  nil : @cname.name %></td>
        <% @cname = Test.find_by id: question.test_id.to_i  %>
        <td><%= @cname.blank? ?  nil : @cname.name %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

costructor/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

costructor/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @question.name %>
</p>

<p>
  <strong>Type of question:</strong>
  <%= @question.type_of_question %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>